ProjectMVC/Models/Contact.cs
using System.ComponentModel.DataAnnotations;

namespace ProjectMVC.Models
{
    public class Contact
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "UserName is Required")]
        public string UserName { get; set; }
        [DataType(DataType.EmailAddress, ErrorMessage = "Please Enter The Vaild Email")]
        [Required(ErrorMessage = "Email is Required")]
        public string Email { get; set; }
        public string? Subject { get; set; }
        public string Message { get; set; }

    }
}

ProjectMVC/Controllers/CampanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectMVC.Models;
using ProjectMVC.Repository;
using ProjectMVC.ViewModel;

namespace ProjectMVC.Controllers
{

    public class CampanyController : Controller
    {
        ICampany _CompanyRepository;
        IJob _JobRepository;

        public CampanyController(ICampany CompanyRepository, IJob JobRepository)
        {
            _CompanyRepository = CompanyRepository;
            _JobRepository = JobRepository;
        }

        public IActionResult Index()
        {

            List<Campany> comListModel = _CompanyRepository.GetAll();
            return View("Index", comListModel);

        }
        public IActionResult GetJobByCatID(int comID)
        {
            var companys = _JobRepository.GetByCatID(comID)
                .Select(e => new { e.Name, e.Id }).ToList();

            return Json(companys);

        }
        public IActionResult CampaniesJob(int CompanyId)
        {
            List<Job> jobs = _JobRepository.GetAll().Where(j => j.CompanyId == CompanyId).ToList();

            return View("CampaniesJob", jobs);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult New()
        {
            return View("New");
        }
        [HttpPost]
        public IActionResult SaveNEw(Campany company)
        {
            if (ModelState.IsValid == true)
            {
                try
                {
                    if (company.Name != null && company.Description != null)
                    {
                        _CompanyRepository.Insert(company);
                        _CompanyRepository.Save();

                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("error", "Name and Description cannot be null");
                        return View("New", company);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("error", ex.InnerException.Message);
                    return View("New", company);
                }
            }
            else
            {
                return View("New", company);
            }
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Campany company = _CompanyRepository.GetById(id);
            if (company == null)
                return NotFound("Company Not Found");

            campanymodel comVM = new campanymodel();
            comVM.Id = company.Id; // Ensure to set the Id in the view model
            comVM.Name = company.Name;
            comVM.Description = company.Description;
            comVM.Jobs = company.Jobs;

            return View("Edit", comVM);
        }

        [HttpPost]
        public IActionResult SaveEdit(campanymodel comview)
        {
            if (comview.Name != null && comview.Description != null)
            {
                // Retrieve the existing company from the repository
                Campany existingCompany = _CompanyRepository.GetById(comview.Id);

                if (existingCompany == null)
                {
                    return NotFound("Company Not Found");
                }

                existingCompany.Name = comview.Name;
                existingCompany.Description = comview.Description;

                _CompanyRepository.Update(existingCompany);
                _CompanyRepository.Save(); // Assuming Save() persists changes to the database

                return RedirectToAction("Index");
            }
            return View("Edit", comview);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            _CompanyRepository.Delete(id);
            _CompanyRepository.Save();
            return RedirectToAction("Index");

        }
    }
}

ProjectMVC/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMVC.Models;
using ProjectMVC.Repository;

namespace ProjectMVC.Controllers
{
    public class ContactController : Controller
    {
        private IContact contactRepository;

        public ContactController(IContact contactRepository)
        {
            this.contactRepository = contactRepository;

        }
        public IActionResult Index()
        {
            return View("Contact");
        }

        public IActionResult Add(Contact newContact)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    contactRepository.Add(newContact);
                    contactRepository.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

            }

            return View("Contact", newContact);

        }
    }
}

ProjectMVC/Controllers/JobController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using ProjectMVC.Hubs;
using ProjectMVC.Models;
using ProjectMVC.Repository;
using ProjectMVC.ViewModel;
namespace ProjectMVC.Controllers
{
    public class JobController : Controller
    {
        ICategory _CategoryRepository;
        IJob _JobRepository;
        IApplyForJob _ApplyForJob;
        ICampany _CompanyRepository;
        IHubContext<jobHub> hubContext;

        public JobController
                (ICategory CategoryRepository, IJob JobRepository, ICampany CompanyRepository, IHubContext<jobHub> _hubContext)
        {
            _CategoryRepository = CategoryRepository;
            _JobRepository = JobRepository;
            _CompanyRepository = CompanyRepository;
            hubContext = _hubContext;

        }


        //public IActionResult Index()
        //{

        //    List<Job> JobListModel = _JobRepository.GetAll();
        //    return View("Index", JobListModel);

        //}

        [HttpGet]
        public IActionResult FullTimeJobIndex()
        {
            List<Job> JobListModel2 = _JobRepository.GetFullTimeJob();
            return View("FullTimeJobIndex", JobListModel2);
        }
        [HttpGet]
        public IActionResult PartTimeJobIndex()
        {
            List<Job> JobListModel1 = _JobRepository.GetPartTimeJob();
            return View("PartTimeJobIndex", JobListModel1);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult New()
        {
            var viewModel = new JobWithCategoryNameVm
            {
                Categories = _CategoryRepository.GetAll(),
                Companies = _CompanyRepository.GetAll()
            };
            return View("NewJob", viewModel);
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public IActionResult SaveNew(JobWithCategoryNameVm jobview)
        {
            if ((ModelState.IsValid == true))
            {
                Job jobmodel = new Job
                {
                    Name = jobview.Name,
                    Description = jobview.Description,
                    Salary = jobview.Salary,
                    Position = jobview.Position,
                    DateTime = jobview.DateTime,
                    CategoryId = jobview.SelectedCategoryId,
                    Type = jobview.Type,
                    Location = jobview.Location,
                    CompanyId = jobview.SelectedCompanyId

                };
                _JobRepository.Insert(jobmodel);
                _JobRepository.Save();

                return RedirectToAction("FullTimeJobIndex");
            }
            return View("NewJob", jobview);
        }


        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {

            var jobToDelete = _JobRepository.GetById(id);
            if (jobToDelete == null)
            {
                return NotFound(); // Or handle not found case as needed
            }
            _JobRepository.Delete(id);

            return RedirectToAction("FullTimeJobIndex");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            Job jobModel = _JobRepository.GetById(id);
            if (jobModel == null)
                return NotFound("job Not Found");
            JobWithCategoryNameVm jobVM = new JobWithCategoryNameVm();
            jobVM.Name = jobModel.Name;
            jobVM.Position = jobModel.Position;
            jobVM.SelectedCategoryId = jobModel.CategoryId;
            jobVM.Salary = jobModel.Salary;
            jobVM.Location = jobModel.Location;
            jobVM.Type = jobModel.Type;
            jobVM.Description = jobModel.Description;
            jobVM.Categories = _CategoryRepository.GetAll();
            jobVM.Companies = _CompanyRepository.GetAll();

            return View("Edit", jobVM);
        }
        [HttpPost]
        public IActionResult SaveEdit(JobWithCategoryNameVm jobview)//Vm
        {
            if (jobview.Name != null && jobview.Description != null)
            {
                Job jobmodel = new Job
                {
                    Name = jobview.Name,
                    Description = jobview.Description,
                    Salary = jobview.Salary,
                    Position = jobview.Position,
                    DateTime = jobview.DateTime,
                    CategoryId = jobview.SelectedCategoryId,
                    Type = jobview.Type,
                    Location = jobview.Location
                    //CompanyId =jobview.SelectedCompanyId

                };
                _JobRepository.Update(jobmodel);
                _JobRepository.Save();

                return RedirectToAction("FullTimeJobIndex");
            }
            return View("Edit", jobview);
        }
        public IActionResult Details(int id)
        {
            Job jobModel = _JobRepository.GetById(id);
            return View("Details", jobModel);
        }

    }
}

ProjectMVC/Views/Shared/_AboutLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<partial name="_HeadPartialView.cshtml" />

<body>

        <!-- Navbar Start -->
        <div class="container-xxl bg-white p-0">
            <!-- Spinner Start -->
            <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
                <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
            <!-- Spinner End -->
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
                <a asp-controller="Home" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5" asp-action="Index">
                <img src="~/img/Logo (2).png" />

                </a>
                <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto p-4 p-lg-0">
                        <a asp-controller="Home" class="nav-item nav-link " asp-action="Index">Home</a>
                    <a asp-controller="About" class="nav-item nav-link active" asp-action="About">About</a>
                    <a asp-controller="Job" class="nav-item nav-link " asp-action="FullTimeJobIndex">
                        Job List
                    </a>
                    <a asp-controller="Home" class="nav-item nav-link  " asp-action="testimonial">Testimonial</a>
                        @* <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
                        <div class="dropdown-menu rounded-0 m-0">
                            <a asp-controller="Job" class="dropdown-item" asp-action="FullTimeJobIndex">Job List</a>
                            <a asp-controller="Job" class="dropdown-item" asp-action="Job_Detail">Job Detail</a>
                        </div>
                        </div> *@
                       @*  <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu rounded-0 m-0">
                                <a asp-controller="Home" class="dropdown-item" asp-action="Category">Category</a>
                                <a asp-controller="Home" class="dropdown-item" asp-action="testimonial">Testimonial</a>
                                <a asp-controller="Home" class="dropdown-item" asp-action="Errors">404</a>
                            </div>
                        </div> *@
                        <a asp-controller="Home" class="nav-item nav-link " asp-action="Contact">Contact</a>
                    </div>
                    <a asp-controller="Home" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block" asp-action="Category">Post A Job<i class="fa fa-arrow-right ms-3"></i></a>
                </div>
        </div>
        </nav>
        <!-- Navbar End -->
      


        <!-- Header End -->
        <div class="container-xxl py-5 bg-dark page-header mb-5">
            <div class="container my-5 pt-5 pb-4">
                <h1 class="display-3 text-white mb-3 animated slideInDown">About Us</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb text-uppercase">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Pages</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">About</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- Header End -->
        @RenderBody()

        <!-- About Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                        <div class="row g-0 about-bg rounded overflow-hidden">
                            <div class="col-6 text-start">
                                <img class="img-fluid w-100" src="/img/about-1.jpg">
                            </div>
                            <div class="col-6 text-start">
                                <img class="img-fluid" src="/img/about-2.jpg" style="width: 85%; margin-top: 15%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid" src="/img/about-3.jpg" style="width: 85%;">
                            </div>
                            <div class="col-6 text-end">
                                <img class="img-fluid w-100" src="/img/about-4.jpg">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                        <h1 class="mb-4">We Help To Get The Best Job And Find A Talent</h1>
                        <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Tempor erat elitr rebum at clita</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Aliqu diam amet diam et eos</p>
                        <p><i class="fa fa-check text-primary me-3"></i>Clita duo justo magna dolore erat amet</p>
                        <a class="btn btn-primary py-3 px-5 mt-3" href="">Read More</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- About End -->


        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Company</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Quick Links</h5>
                        <a class="btn btn-link text-white-50" href="">About Us</a>
                        <a class="btn btn-link text-white-50" href="">Contact Us</a>
                        <a class="btn btn-link text-white-50" href="">Our Services</a>
                        <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                        <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Contact</h5>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h5 class="text-white mb-4">Newsletter</h5>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 

                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/lib/wow/wow.min.js"></script>
    <script src="/lib/easing/easing.min.js"></script>
    <script src="/lib/waypoints/waypoints.min.js"></script>
    <script src="/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="/js/main.js"></script>
</body>

</html>

ProjectMVC/Views/Shared/_HeadPartialView.cshtml
<head>
    <meta charset="utf-8">
    @* <title>JobEntry - Job Portal Website Template</title> *@
    
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/css/style.css" rel="stylesheet">
</head>

ProjectMVC/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<partial name="_HeadPartialView.cshtml" />

<div class="container-xxl bg-white p-0">
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
        <a asp-controller="Home" class="navbar-brand d-flex align-items-center text-center py-0 px-4 px-lg-5" asp-action="Index">
            @* <h1 class="m-0 text-primary">JobEntry</h1> *@
            <img src="~/img/Logo (2).png" />
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a asp-controller="Home" class="nav-item nav-link active" asp-action="Index">Home</a>
                <a asp-controller="Home" class="nav-item nav-link" asp-action="About">About</a>
                <a asp-controller="Job" class="nav-item nav-link " asp-action="FullTimeJobIndex">
                    Job List
                </a>
                <a asp-controller="Campany" class="nav-item nav-link  " asp-action="Index">company</a>
                                <a asp-controller="Category" class="nav-item nav-link  " asp-action="Index">Category</a>

                @* <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Jobs</a>
                <div class="dropdown-menu rounded-0 m-0">
                <a asp-controller="Job" class="dropdown-item" asp-action="FullTimeJobIndex">Job List</a>
                <a asp-controller="Job" class="dropdown-item" asp-action="Job_Detail">Job Detail</a>
                </div>
                </div> *@
                @*   <div class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                <div class="dropdown-menu rounded-0 m-0">
                <a asp-controller="Category" class="dropdown-item" asp-action="Index">Category</a>
                <a asp-controller="Home" class="dropdown-item" asp-action="testimonial">Testimonial</a>
                <a asp-controller="Home" class="dropdown-item" asp-action="Errors">404</a>
                <a asp-controller="Home" class="dropdown-item" asp-action="Campany">Campany</a>

                </div>
                </div> *@
                <a asp-controller="Home" class="nav-item nav-link" asp-action="Contact">Contact</a>
                <partial name="_LoginPartial"></partial>
            </div>
            @*  <a asp-controller="Home" class="btn btn-primary rounded-0 py-4 px-lg-5 d-none d-lg-block"
            asp-action="Category">Post A Job<i class="fa fa-arrow-right ms-3"></i></a> *@
        </div>
    </nav>
  
    @RenderBody()




    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Company</h5>
                    <a class="btn btn-link text-white-50" href="">About Us</a>
                    <a class="btn btn-link text-white-50" href="">Contact Us</a>
                    <a class="btn btn-link text-white-50" href="">Our Services</a>
                    <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                    <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Quick Links</h5>
                    <a class="btn btn-link text-white-50" href="">About Us</a>
                    <a class="btn btn-link text-white-50" href="">Contact Us</a>
                    <a class="btn btn-link text-white-50" href="">Our Services</a>
                    <a class="btn btn-link text-white-50" href="">Privacy Policy</a>
                    <a class="btn btn-link text-white-50" href="">Terms & Condition</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Contact</h5>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5 class="text-white mb-4">Newsletter</h5>
                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

                        <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                        Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/lib/wow/wow.min.js"></script>
    <script src="/lib/easing/easing.min.js"></script>
    <script src="/lib/waypoints/waypoints.min.js"></script>
    <script src="/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="/js/main.js"></script>


</html>